[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "langchain-kinetica"
description = "An integration package connecting Kinetica and LangChain"
license = { text = "MIT" }
readme = "README.md"
authors = [
    {name = "Chad Juliano", email = "cjuliano@kinetica.com"},
    {name = "Anindya Mukherjee", email = "amukherjee@kinetica.com"},
]
version = "1.3.0"
requires-python = ">=3.10.0,<4.0.0"
dependencies = [
    "langchain-core>=1.1.0,<2.0.0",
    "gpudb[dataframe] >= 7.1.9.10",
    "pandas>=2.2.0,<3.0.0",
]

[project.urls]
Homepage = "https://kinetica.com"
Documentation = "http://localhost:3000/oss/python/integrations/chat/kinetica"
Repository = "https://github.com/kineticadb/langchain-kinetica"

[dependency-groups]
test = [
    "pytest>=7.4.3,<8.0.0",
    "pytest-asyncio>=0.23.2,<1.0.0",
    "pytest-socket>=0.7.0,<1.0.0",
    "faker>=40.1.2",
    "langchain-openai>=1.1.7",
    "langchain-text-splitters>=1.1.0",
    "langchain-community>=0.4.1",
    "build>=1.4.0",
]
jupyter = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "nbconvert>=7.17.0",
]
lint = ["ruff>=0.13.1,<0.14.0"]
typing = ["mypy>=1.10.0,<2.0.0"]
dev = [
  {include-group = "lint"},
  {include-group = "test"},
  {include-group = "typing"},
  {include-group = "jupyter"},
]

[tool.coverage.run]
omit = ["tests/*"]

[tool.pytest.ini_options]
addopts = "--strict-markers --strict-config --durations=5"
markers = [
    "compile: mark placeholder test used to compile integration tests without running them",
]
asyncio_mode = "auto"
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(levelname)s [%(name)s] %(message)s"

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.ruff]
extend-exclude = ["notebooks/kinetica_provider.ipynb"] # don't remove unused imports

[tool.ruff.format]
docstring-code-format = false
docstring-code-line-length = 100

[tool.ruff.lint]
select = [ "ALL" ]
ignore = [
    "COM812",  # Conflicts with formatter
    "PLR0913", # Too many arguments
    "TRY003",
    "ERA001", # Found commented-out code

    # TODO
    "ANN401",
]
#unfixable = ["B028"]

[tool.ruff.lint.pydocstyle]
convention = "google"
ignore-var-parameters = true  # ignore missing documentation for *args and **kwargs parameters

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*.py" = [
    "S101",   # Tests need assertions
    "S311",   # Standard pseudo-random generators are not suitable for cryptographic purposes
    "SLF001", # Private member access
]
"scripts/*.py" = [
    "INP001",   # Not a package
]
"notebooks/*.ipynb" = [
    "D103",  # Missing docstring
    "T201",  # print found
    "S608",  # Possible SQL injection
]
